services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      proxy_network:
        ipv4_address: 172.18.0.10
    restart: always

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=digitialmarket1810@proton.me
    depends_on:
      - nginx-proxy
    volumes_from:
      - nginx-proxy
    volumes:
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy_network
    restart: always

  project1:
    build:
      context: ../projects/copy
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=docker.lostcanbefound.info
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=docker.lostcanbefound.info
      - LETSENCRYPT_EMAIL=digitialmarket1810@proton.me
    expose:
      - "5000"
    networks:
      proxy_network:
        ipv4_address: 172.18.0.2
    restart: always

  project2:
    build:
      context: ../projects/MotorFinanceTracker
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=docker.5th4.com
      - VIRTUAL_PORT=5001
      - LETSENCRYPT_HOST=docker.5th4.com
      - LETSENCRYPT_EMAIL=digitialmarket1810@proton.me
    expose:
      - "5001"
    ports:
      - "5001:5001"
    networks:
      proxy_network:
        ipv4_address: 172.18.0.4
    restart: always

volumes:
  certs:
  vhost:
  html:
  acme:

networks:
  proxy_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
