services:
  nginx1:
    image: nginxproxy/nginx-proxy
    container_name: nginx1
    ports:
      - "193.151.108.62:80:80"
      - "193.151.108.62:443:443"
    volumes:
      - certs1:/etc/nginx/certs
      - vhost1:/etc/nginx/vhost.d
      - html1:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - net1
    restart: always

  acme1:
    image: nginxproxy/acme-companion
    container_name: acme1
    environment:
      - DEFAULT_EMAIL=digitialmarket1810@proton.me
    volumes_from:
      - nginx1
    volumes:
      - acme1:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net1
    restart: always

  project1:
    build:
      context: ../projects/Paymenth1
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=forumonline.click
      - VIRTUAL_PORT=5000 
      - LETSENCRYPT_HOST=forumonline.click
      - LETSENCRYPT_EMAIL=digitialmarket1810@proton.me
      - PORT = 5000
    expose:
      - "5000"
    networks:
      - net1
    restart: always
  
  server-socket-project1:
    build:
      context: ../projects/server-socket-Paymenth1
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=server-sockets.forumonline.click
      - LETSENCRYPT_HOST=server-sockets.forumonline.click
      - SOCKET_PORT=5001
      - SOCKET_HOST=0.0.0.0
      - CLIENT_URL=https://forumonline.click
    expose:
      - "5001"
    networks:
      - net1
    restart: always

  nginx2:
    image: nginxproxy/nginx-proxy
    container_name: nginx2
    ports:
      - "213.21.237.35:80:80"
      - "213.21.237.35:443:443"
    volumes:
      - certs2:/etc/nginx/certs
      - vhost2:/etc/nginx/vhost.d
      - html2:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - net2
    restart: always

  acme2:
    image: nginxproxy/acme-companion
    container_name: acme2
    environment:
      - DEFAULT_EMAIL=digitialmarket1810@proton.me
    volumes_from:
      - nginx2
    volumes:
      - acme2:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net2
    restart: always

  project2:
    build:
      context: ../projects/Paymenth2
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=forumparati.forum
      - VIRTUAL_PORT=5002
      - LETSENCRYPT_HOST=forumparati.forum
      - LETSENCRYPT_EMAIL=digitialmarket1810@proton.me
      - PORT = 5002
    expose:
      - "5002"
    networks:
      - net2
    restart: always

  server-socket-project2:
    build:
      context: ../projects/server-socket-Paymenth2
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=server-sockets.forumparati.forum
      - LETSENCRYPT_HOST=server-sockets.forumparati.forum
      - SOCKET_PORT=5003
      - SOCKET_HOST=0.0.0.0
      - CLIENT_URL=https://forumparati.forum
    expose:
      - "5003"
    networks:
      - net2
    restart: always

volumes:
  certs1:
  vhost1:
  html1:
  acme1:
  certs2:
  vhost2:
  html2:
  acme2:

networks:
  net1:
  net2:
