services:
  nginx1:
    image: nginxproxy/nginx-proxy
    container_name: nginx1
    ports:
      - "193.151.108.62:80:80"
      - "193.151.108.62:443:443"
    volumes:
      - certs1:/etc/nginx/certs
      - vhost1:/etc/nginx/vhost.d
      - html1:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - net1
    restart: always

  acme1:
    image: nginxproxy/acme-companion
    container_name: acme1
    environment:
      - DEFAULT_EMAIL=digitialmarket1810@proton.me
    volumes_from:
      - nginx1
    volumes:
      - acme1:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net1
    restart: always

  project1:
    build:
      context: ../projects/paymenth-nuxt-jkr1
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=cydercup.com
      - VIRTUAL_PORT=5000 
      - LETSENCRYPT_HOST=cydercup.com
      - LETSENCRYPT_EMAIL=digitialmarket1810@proton.me
    expose:
      - "5000"
    networks:
      - net1
    restart: always

  server-sockets-farid-oswaldo-roman-upegui-marin-jkr1:
    image: server-sockets-farid-oswaldo-roman-upegui-marin-jkr1
    build:
      context: ../projects/server-sockets-farid-oswaldo-roman-upegui-marin-jkr1
    restart: always
    expose:
      - '3001'
    environment:
      - VIRTUAL_HOST=server-sockets.cydercup.com
      - LETSENCRYPT_HOST=server-sockets.cydercup.com
      - SOCKET_PORT=3001
      - SOCKET_HOST=0.0.0.0
      - CLIENT_URL=https://cydercup.com
    networks:
      - net1

  nginx2:
    image: nginxproxy/nginx-proxy
    container_name: nginx2
    ports:
      - "213.21.237.35:80:80"
      - "213.21.237.35:443:443"
    volumes:
      - certs2:/etc/nginx/certs
      - vhost2:/etc/nginx/vhost.d
      - html2:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - net2
    restart: always

  acme2:
    image: nginxproxy/acme-companion
    container_name: acme2
    environment:
      - DEFAULT_EMAIL=digitialmarket1810@proton.me
    volumes_from:
      - nginx2
    volumes:
      - acme2:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net2
    restart: always

  project2:
    build:
      context: ../projects/paymenth-nuxt-jkr2
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=qwerss.shop
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=qwerss.shop
      - LETSENCRYPT_EMAIL=digitialmarket1810@proton.me
    expose:
      - "5000"
    networks:
      - net2
    restart: always

  server-sockets-farid-oswaldo-roman-upegui-marin-jkr2:
    image: server-sockets-farid-oswaldo-roman-upegui-marin-jkr2
    build:
      context: ../projects/server-sockets-farid-oswaldo-roman-upegui-marin-jkr1
    restart: always
    expose:
      - '3001'
    environment:
      - VIRTUAL_HOST=server-sockets.qwerss.shop
      - LETSENCRYPT_HOST=server-sockets.qwerss.shope
      - SOCKET_PORT=3001
      - SOCKET_HOST=0.0.0.0
      - CLIENT_URL=https://qwerss.shop
    networks:
      - net2
  # nginx3:
  #   image: nginxproxy/nginx-proxy
  #   container_name: nginx3
  #   ports:
  #     - "213.21.237.72:80:80"
  #     - "213.21.237.72:443:443"
  #   volumes:
  #     - certs3:/etc/nginx/certs
  #     - vhost3:/etc/nginx/vhost.d
  #     - html3:/usr/share/nginx/html
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #   networks:
  #     - net3
  #   restart: always

  # acme3:
  #   image: nginxproxy/acme-companion
  #   container_name: acme3
  #   environment:
  #     - DEFAULT_EMAIL=tu@email.com
  #   volumes_from:
  #     - nginx3
  #   volumes:
  #     - acme3:/etc/acme.sh
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   networks:
  #     - net3
  #   restart: always

  # project3:
  #   build:
  #     context: ../projects/Paymenth
  #     dockerfile: Dockerfile
  #   environment:
  #     - VIRTUAL_HOST=dominio3.com
  #     - VIRTUAL_PORT=5000
  #     - LETSENCRYPT_HOST=dominio3.com
  #     - LETSENCRYPT_EMAIL=tu@email.com
  #   expose:
  #     - "5000"
  #   networks:
  #     - net3
  #   restart: always

volumes:
  certs1:
  vhost1:
  html1:
  acme1:
  certs2:
  vhost2:
  html2:
  acme2:
  # certs3:
  # vhost3:
  # html3:
  # acme3:

networks:
  net1:
  net2:
  # net3:
