services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=digitialmarket1810@proton.me
    volumes_from:
      - nginx-proxy
    volumes:
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  project1:
    build:
      context: ../projects/Paymenth
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=somepeoplelie.info
      - VIRTUAL_PORT=5000 
      - LETSENCRYPT_HOST=somepeoplelie.info
      - LETSENCRYPT_EMAIL=digitialmarket1810@proton.me
    expose:
      - "5000"
    restart: always

  # project2:
  #   build:
  #     context: ../projects/copy
  #     dockerfile: Dockerfile
  #   environment:
  #     - VIRTUAL_HOST=somepeoplelie.info
  #     - VIRTUAL_PORT=5001 
  #     - LETSENCRYPT_HOST=somepeoplelie.info
  #     - LETSENCRYPT_EMAIL=digitialmarket1810@proton.me
  #   expose:
  #     - "5001"
  #   restart: always


volumes:
  conf:
  vhost:
  html:
  certs:
  acme:
