services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=digitialmarket1810@proton.me
    volumes_from:
      - nginx-proxy
    volumes:
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  project1:
    build:
      context: ../projects/copy
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=docker.lostcanbefound.info
      - VIRTUAL_PORT=5000 
      - LETSENCRYPT_HOST=docker.lostcanbefound.info
      - LETSENCRYPT_EMAIL=digitialmarket1810@proton.me
    expose:
      - "5000"
    restart: always

  project2:
    build:
      context: ../projects/MotorFinanceTracker
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=docker.5th4.com
      - VIRTUAL_PORT=5001
      - LETSENCRYPT_HOST=docker.5th4.com
      - LETSENCRYPT_EMAIL=digitialmarket1810@proton.me
    expose:
      - "5001"
    restart: always

  project3:
    build:
      context: ../projects/GiftCardExplorer
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=gifcards.5th4.com
      - VIRTUAL_PORT=5002
      - LETSENCRYPT_HOST=gifcards.5th4.com
      - LETSENCRYPT_EMAIL=digitialmarket1810@proton.me
    expose:
      - "5002"
    restart: always

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:
