services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      proxy_network_1:
        ipv4_address: 172.31.13.218
      proxy_network_2:
        ipv4_address: 172.31.12.194
    restart: always

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=digitialmarket1810@proton.me
    volumes_from:
      - nginx-proxy
    volumes:
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy_network_1
      - proxy_network_2
    restart: always

  project1:
    build:
      context: ../projects/copy
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=docker.lostcanbefound.info
      - VIRTUAL_PORT=5000 
      - LETSENCRYPT_HOST=docker.lostcanbefound.info
      - LETSENCRYPT_EMAIL=digitialmarket1810@proton.me
    expose:
      - "5000"
    networks:
      proxy_network_1:
        ipv4_address: 172.31.13.219
    restart: always
    mem_limit: 512m
    cpus: 0.5

  project2:
    build:
      context: ../projects/MotorFinanceTracker
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=tp659.com
      - VIRTUAL_PORT=5001
      - LETSENCRYPT_HOST=tp659.com
      - LETSENCRYPT_EMAIL=digitialmarket1810@proton.me
    expose:
      - "5001"
    networks:
      proxy_network_2:
        ipv4_address: 172.31.12.220
    restart: always
    mem_limit: 512m
    cpus: 0.5

networks:
  proxy_network_1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.13.0/24
          gateway: 172.31.13.1
  proxy_network_2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.12.0/24
          gateway: 172.31.12.1

volumes:
  conf:
  vhost:
  html:
  certs:
  acme: